name: desktop_widgets
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  collection: ^1.16.0
  desktop_multi_window: ^0.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  helpers:
    git:
      url: https://github.com/Merrit/helpers.git
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  logging: ^1.0.2
  path_provider: ^2.0.11
  tray_manager: ^0.1.8
  uuid: ^3.0.6
  window_manager: ^0.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/icons/
