name: desktop_widgets
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_acrylic: 0.0.2
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  percent_indicator: ^3.4.0
  system_tray: ^0.1.0
  uuid: ^3.0.6
  window_manager: ^0.2.0
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a550668ca25881d154ae54204baa93a41fe5e344

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/app_icon.png
